### PR TITLE
Leaderboard: final touches

### PR DESCRIPTION
**Pull request by mirouhml**
- Improve the look and feel of the web application.
- Add loading animations.
- Using setTimeout instead of the previous setInterval to remove text from input fields.

### CODE REVIEW

**Review by rotimiazeez — CHANGES_REQUESTED** [review]
Hi @mirouhml 👋🏽, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

- Please make sure the README file looks professional and contains all that's needed for running the app with the API(s) it consumes. It should have instructions about where and how to generate any necessary keys, credentials, how to set, store, and generate them(if necessary). 😉 ✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mirouhml** [comment]
Hello @rotimiazeez thanks for the review!
Regarding the changes you requested, the API doesn't have any keys or credentials, it's a basic public API for the leaderboard, we didn't have any requirement about this in the project requirements, would you please explain to me what you meant?

**Comment by mirouhml** [comment]
I updated my README to include the documentation page of the API.

**Review by rotimiazeez — APPROVED** [review]
# Hi @mirouhml 👋🏽, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mirouhml** [comment]
Thanks again!

**Pull request merged**
